name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install node dependencies
      run: npm install

    - name: Build Tailwind CSS
      run: npm run build

    - name: Deploy Serverless
      run: ./node_modules/.bin/sls deploy --stage=prod
